### ISSUE TITLE
Use shift-wheel to zoom in linechart

### ISSUE THREAD

**Issue by bures** [smartarch/ivis-core#55]
At present, one can zoom-in/out in line-charts using a mouse wheel. This however interferes with longer panels in which one has to scroll. It would be good to distinguish zoom in/out vs. page scrolling (e.g. similar to how embedded google maps do it).

**Comment by Mnaukal** [comment]
I assume we want the same behaviour across all the charts (linechart, scatterplot, ...). I will look at it.

It should currently be possible to scroll the page if you scroll the wheel outside of the chart.

**Comment by bures** [comment]
Yep. To have the same in the other charts would be nice. Thanks.

Regarding the scrolling - I am aware of that. But for instance if one scrolls with mouse over the axis, it still zooms in the graph. That makes it a bit difficult to scroll on a  page. Thanks.
